### ISSUE TITLE
generates rust struct from Multiple XML schemas (xsd files)

### ISSUE THREAD

**Issue by claudiofsr** [Thomblin/xml_schema_generator#11]
Firstly, excellent work! Congratulations!

Up to now I need [xsd2inst](https://xmlbeans.apache.org/docs/2.0.0/guide/tools.html#xsd2inst) (Schema to Instance Tool) from Apache XMLBeans.

xsd2inst prints an XML instance from the specified global element using the specified schema.

XSD to XML:
```
/xmlbeans-5.2.0/bin/xsd2inst file.xsd -name Some_Name -dl > file.xml
```

And then:
```
xml_schema_generator file.xml my_struct.rs
```
Could it be implemented as input XSD files?

**Comment by Thomblin** [comment]
Thanks for your compliment.

Parsing an XML and parsing an XSD sounds like two completely different challenges. Did you already try crates like https://github.com/lumeohq/xsd-parser-rs? I found some more but this looks like it is maintained at least.

Else: All partners that I work with are not providing XSD files. Thus I am not sure if I would take the effort to introduce another level of complexity to this library. However you are welcome to contribute with PR here

**Comment by claudiofsr** [comment]
I will try "xsd-parser-rs".
Thanks.
