### ISSUE TITLE
`<text>` Tags Improperly Generated

### ISSUE THREAD

**Issue by abhillman** [Thomblin/xml_schema_generator#37]
**Observed**

```bash
$ cat example.xml
<example>
    <text bytes="5">hello</text>
</example>
$ xml_schema_generator example.xml
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "$text")]
    pub text: Option<String>,
    pub text: Text,
}

#[derive(Serialize, Deserialize)]
pub struct Text {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}
```

**Expected**

```bash
$ xml_schema_generator example.xml
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Example {
    pub text: Text,
}

#[derive(Serialize, Deserialize)]
pub struct Text {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}
```

**Version**

```bash
$ xml_schema_generator --version    
xml_schema_generator 0.6.11
```

**Other info**

Wikimedia's archive format is an example of a XML schema that includes `<text ...>` tags https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/docs/export-0.11.xsd#197, https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/docs/export-0.11.xsd#258

**Comment by Thomblin** [comment]
Thanks for your report. 

The issue here is that whitespaces are preserved. It works with `<example><text bytes=\"5\">hello</text></example>`

I am thinking: Is your expected output correct? 

Given something like `<example>hello<text bytes=\"5\">world</text></example>` the expected output might be something like

```
#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "$text")]
    pub text_attr: Option<String>,
    pub text: Text,
}
```

instead of 

```
#[derive(Serialize, Deserialize)]
pub struct Example {
    pub text: Text,
}
```

which raises the follow up question: how should be parse `<example>hello<text_attr bytes=\"5\">world</text></example>` where the child name text_attr collides with the example.text attribute ... ?

I am open for ideas. I added a fix for your issue in the related branch, however this would just ignore text attributes if a child with name text exists

**Comment by Thomblin** [comment]
Thinking further, I do not detect collissions of attributs and children yet:
```
<example foo="bar">
    <foo bytes="5">hello</foo>
</example>
```

gives

```
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "@foo")]
    pub foo: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
    pub foo: Foo,
}

#[derive(Serialize, Deserialize)]
pub struct Foo {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}```

but should be something like

```
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "@foo")]
    pub foo: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
    pub example_foo: Foo,
}

#[derive(Serialize, Deserialize)]
pub struct Foo {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}```

**Comment by Thomblin** [comment]
I guess I found a good solution:

```
<example>
    <text bytes="5">hello</text>
</example>
```

will now be represented with

use serde::{Deserialize, Serialize};

```
#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "$text")]
    pub text_content: Option<String>,
    pub text: Text,
}

#[derive(Serialize, Deserialize)]
pub struct Text {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}
```

and something like

```
<example foo="bar">
    <foo bytes="5">hello</foo>
</example>
```

creates

```
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Example {
    #[serde(rename = "@foo")]
    pub foo_attr: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
    pub foo: Foo,
}

#[derive(Serialize, Deserialize)]
pub struct Foo {
    #[serde(rename = "@bytes")]
    pub bytes: String,
    #[serde(rename = "$text")]
    pub text: Option<String>,
}
```
