### ISSUE TITLE
Structure names are missing if fields are named in Cyrillic.

### ISSUE THREAD

**Issue by indieleet** [Thomblin/xml_schema_generator#40]
We have this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<КоммерческаяИнформация>
	<Классификатор>
		<Ид>1</Ид>
		<Наименование>Классификатор</Наименование>
		<Владелец>Булат</Владелец>
	</Классификатор>
</КоммерческаяИнформация>
```
Output:
```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct  {
    #[serde(rename = "$text")]
    pub text: Option<String>,
    #[serde(rename = "Классификатор")]
    pub К_: ,
}

#[derive(Serialize, Deserialize)]
pub struct  {
    #[serde(rename = "$text")]
    pub text: Option<String>,
    #[serde(rename = "Ид")]
    pub И_: String,
    #[serde(rename = "Наименование")]
    pub Н_: String,
    #[serde(rename = "Владелец")]
    pub В_: String,
}
```

**Comment by Thomblin** [comment]
@indieleet Thanks for the report. I struggle a bit here as I am not used to cyrillic. Are you aware of a suitable rust library or methods to convert cyrillic characters (lowercase, uppercase, detect alphanumeric characters, ...)

**Comment by indieleet** [comment]
@Thomblin i think that you need something like this https://github.com/kornelski/deunicode because I don't think this bug is specific to Cyrillic only

**Comment by Thomblin** [comment]
@indieleet Thanks for your reply. I'll take that into consideration if further problems occur. For now I guess I found a quite simple solution for your case (I pushed a new version) unless you prefer to have ascii names. I could imagine to use deunicode optionally as a feature flag

**Comment by indieleet** [comment]
@Thomblin thank you! Everything works fine now! No need for flag for this feature for me
